# Image upload
kms_froala_editor_upload_image:
    pattern: /upload_image
    defaults: { _controller: KMSFroalaEditorBundle:Media:uploadImage }
    options:
        expose: true

kms_froala_editor_delete_image:
    pattern: /delete_image
    defaults: { _controller: KMSFroalaEditorBundle:Media:deleteImage }
    options:
        expose: true